// Generated by Wrangler by running `wrangler types`

interface Env {
	CACHE: KVNamespace;
	USERS: KVNamespace;
	ENVIRONMENT: "production";
	ANTHROPIC_API_KEY: string;
	SUPERMEMORY_API_KEY: string;
	JWT_SECRET: string;
	PHOTOS: R2Bucket;
}
